### ISSUE TITLE
Confused about how to construct latent features

### ISSUE THREAD

**Issue by hedgy123** [evison/JRL#1]
Hi,

   I am trying to follow the steps in JRL_Model/README.txt, and I am confused about "Match rating features".   It says "Construct latent representations based on rating information with any method you like (e.g. BPR)", so I tried to follow the instructions in BPR:

     ./train wholeData trainData testData imageFile latentFactor visualLatentFactor biasReg lambdaReg lambda2Reg epoch iteration outputPath

   but I am confused as to what wholeData, trainData, testData, and imageFile are relative to what I had made in JRL_Model's steps 1 and 2, where I indexed the data and split it into training and testing.   Those steps resulted in a directory (indexed_data...) with the following files:

    product.txt		
    review_id.txt		
    review_u_p.txt		
    test.txt		
    train.txt		
    users.txt
    product_image_feature.b	
    review_text.txt		
    test.qrels		
    test_id.txt		
    train_id.txt		
    vocab.txt
  
  so there are training and testing files here too, but I don't think they are in the format that BPR needs.   Could you please help?   Thanks so much!

**Comment by QingyaoAi** [comment]
You are right, the format used by JRL is different from the format used by BPR. To train BPR (or other models based on rating information), you need to read the user-item pairs in the training/testing data for JRL (train_id.txt and test_id.txt) and generate the data for BPR by youself. The format for those files are:
    <user_idx>\t<product_idx>\tline_<review_idx>
<user_idx> and <product_idx> are the line number (start from 0) for the user and product in users.txt and product.txt. "line_<review_idx>" is the line number (start from 0) of the review data in the original Amazon data.

**Comment by dmalagarriga** [comment]
Hi, 
I am trying to reproduce the results from the paper "Learning Heterogeneous Knowledge Base Embeddings for Explainable Recommendation". I downloaded the Amazon dataset in https://www.dropbox.com/s/th672ttebwxhsfx/CIKM2017.zip?dl=0 and I saw that only for the first dataset domain ( Beauty ) user_factors.csv and item_factors.csv are provided. It seems that I should be constructing the matrices myself for the other domains in the dataset but I don't know how to do it. I was thinking on using BPR but I got stuck into understanding the way to use it. Could you please help?

thanks!!
